import { Inter } from "next/font/google";
import './globals.scss'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    favicon: "/favicon.ico",
    msapplicationTileColor: "#000000",
    msapplicationTileImage: "/mstile-144x144.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
